name: Update Cachy Files with Latest Releases

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '30 5,17 * * *'

  
jobs:
  update-cachy:

    runs-on: ubuntu-latest
      
    steps:

    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Find PKGBUILD Files, Check and Update Latest Release
      run: |
        echo $PWD
        touch ../dirs_to_commit.txt
        while IFS= read -r dir; do
          find "$dir" -name '*PKGBUILD' -not -path '*/-git/*' | while read pkgbuild; do
            echo "Processing $pkgbuild"
            url=$(grep -oP 'url=\K.*' "$pkgbuild")
            current_release=$(grep -oP 'pkgver=\K.*' "$pkgbuild")
            echo "Configured URL: $url"
            echo "Current Release: $current_release"

            # Extract owner and repo from URL
            owner_repo=$(echo "$url" | sed "s/.*github\.com\/\([^']*\).*/\1/")
            echo "Owner/Repo: $owner_repo"

            # Use GitHub API to get the latest release  
            latest_release=$(curl -s "https://api.github.com/repos/$owner_repo/releases/latest" | grep -oP '"tag_name": "\K(.*)(?=")')
            echo "Latest Release: $latest_release"

            # Remove leading 'v' if present 
            latest_release_formatted=$(echo $latest_release | sed 's/^v//')

            echo "Latest Release (formatted): $latest_release_formatted"

            # Check if the current release is different from the latest release
            if [ "$current_release" != "$latest_release_formatted" ]; then
              echo "Updating PKGBUILD file with latest release"
 
              # add dir to list of dirs to commit
              $dirname >> ../dirs_to_commit.txt

              # Check for PKGBUILD file in the same directory
              pkgbuild_file="$(dirname "$pkgbuild")/PKGBUILD"
              echo "Updating PKGBUILD file with latest release and resetting pkgrel to 1"
              sed -i "s/pkgver=$current_release/pkgver=$latest_release_formatted/" "$pkgbuild_file"
              sed -i "s/pkgrel=.*/pkgrel=1/" "$pkgbuild_file"
              git add "$pkgbuild_file"

            fi
            echo "-----------------------------------"
          done
        done < pkgs_to_check.txt
        export ROOT_DIR=/home/runner/work
        echo $PWD

        mkdir -p $ROOT_DIR/to_commit
        
        while read line; do
          cp -r $ROOT_DIR/CachyOS-PKGBUILDS/CachyOS-PKGBUILDS/$line $ROOT_DIR/to_commit
        done < ../dirs_to_commit.txt

    - name: Checkout Master Branch
      uses: actions/checkout@v4
      with:
        ref: master


    - name: Commit and Push Changes
      run: |
       export ROOT_DIR=/home/runner/work
       cp -r $ROOT_DIR/to_commit/* $ROOT_DIR/CachyOS-PKGBUILDS/CachyOS-PKGBUILDS/
       cd $ROOT_DIR/CachyOS-PKGBUILDS/CachyOS-PKGBUILDS/    

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v5
      with:
        commit-message: update .cachy files with latest releases
        title: Update Packages with Latest Releases