name: Update Cachy Files with Latest Releases

on: [push, pull_request]

jobs:
  update-cachy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Find .cachy Files, Check and Update Latest Release
      run: |
        find . -name '*.cachy' -not -path '*/-git/*' | while read cachy; do
          echo "Processing $cachy"
          url=$(grep -oP 'url=\K.*' "$cachy")
          current_release=$(grep -oP 'release=\K.*' "$cachy")
          echo "Configured URL: $url"
          echo "Current Release: $current_release"

          # Extract owner and repo from URL
          owner_repo=$(echo $url | sed -n 's|.*github.com/\(.*\)\.git|\1|p')

          # Use GitHub API to get the latest release
          latest_release=$(curl -s "https://api.github.com/repos/$owner_repo/releases/latest" | grep -oP '"tag_name": "\K(.*)(?=")')

          # Remove leading 'v' if present
          latest_release_formatted=$(echo $latest_release | sed 's/^v//')

          echo "Latest Release (formatted): $latest_release_formatted"

          # Check if the current release is different from the latest release
          if [ "$current_release" != "$latest_release_formatted" ]; then
            echo "Updating .cachy file with latest release"
            sed -i "s/release=$current_release/release=$latest_release_formatted/" "$cachy"
            git add "$cachy"
            # add dir to list of dirs to commit
            $dirname >> ../dirs_to_commit.txt

            # Check for PKGBUILD file in the same directory
            pkgbuild_file="$(dirname "$cachy")/PKGBUILD"
            if [ -f "$pkgbuild_file" ]; then
              echo "Updating PKGBUILD file with latest release and resetting pkgrel to 1"
              sed -i "s/pkgver=$current_release/pkgver=$latest_release_formatted/" "$pkgbuild_file"
              sed -i "s/pkgrel=.*/pkgrel=1/" "$pkgbuild_file"
              git add "$pkgbuild_file"
            fi
          fi
          echo "-----------------------------------"
        done

    
    - name: Checkout Source Repository
      uses: actions/checkout@v4
      with:
        repository: 'CachyOS/CachyOS-PKGBUILDS'
        path: 'CachyOS-PKGBUILDS'

    - name: Copy Files and Commit Changes
      run: |
        echo "ripgrep-pgo" > dirs_to_commit.txt
        echo $PWD
        cd CachyOS-PKGBUILDS
        $echo $PWD
        git checkout -b bump-packages
        # copy files in dirs_to_commit.txt to target repo
        while read line; do
          cp ../PKGBUILDs/$line $line
        done < ../dirs_to_commit.txt
        git add .
        git commit -m "Add updated files"
      
    - name: Push Changes to Target Repository
      run: |
        # push the changes to the new branch
        git push origin HEAD:bump-packages
      env:
        GITHUB_TOKEN: ${{ secrets.TARGET_REPO_PAT }}

    - name: Create Pull Request in Target Repository
      uses: peter-evans/create-pull-request@v3
      with:
        token: ${{ secrets.TARGET_REPO_PAT }}
        base: 'main' # Base branch in the target repo
        title: 'Update Packages with Latest Releases'

